apiVersion: skaffold/v2alpha4
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: 108814617702.dkr.ecr.us-east-1.amazonaws.com/ecommerce-backend
      context: backend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: 108814617702.dkr.ecr.us-east-1.amazonaws.com/ecommerce-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
