apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: frontend
          # image: jared0306/frontend
          image: public.ecr.aws/l5h0a1q6/ecommerce-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-srv
spec:
  selector:
    component: web
  ports:
    - port: 3000
      targetPort: 3000
