apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::108814617702:user/github-ci 
      username: designated_user 
      groups: 
        - system:masters
