name: deploy-frontend
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
jobs:
  build:
    name: Build frontend image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # for private repo
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # for public repo
      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
        env:
          AWS_REGION: us-east-1

      - name: Build, tag, and push image to Amazon ECR
        env:
          # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REGISTRY: public.ecr.aws/l5h0a1q6
          ECR_REPOSITORY: ecommerce-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          docker build -f Dockerfile.dev -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Update kube config
        run: aws eks update-kubeconfig --name ecommerce-fullstack --region us-east-2

      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f infra/eks/aws-auth.yaml
          kubectl rollout restart deployment frontend-depl
